name: Run Create Collection

on:
  # schedule:
  #   - cron: '0 0 * * *'  # This cron expression runs the workflow every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  manage-collection:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/Scripts/IndexTools

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r ${{ github.workspace }}/Scripts/IndexTools/requirements.txt

    - name: Drop Collection
      env:
        TYPESENSE_HOST: ${{ vars.TYPESENSE_HOST }}
        TYPESENSE_SEARCH_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
        TYPESENSE_COLLECTION: ${{ vars.TYPESENSE_COLLECTION }}
      run: python DropCollection.py

    - name: Create Collection
      env:
        TYPESENSE_HOST: ${{ vars.TYPESENSE_HOST }}
        TYPESENSE_SEARCH_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
        TYPESENSE_COLLECTION: ${{ vars.TYPESENSE_COLLECTION }}
      run: python CreateCollection.py

    - name: Import APISpec Data
      env:
        TYPESENSE_HOST: ${{ vars.TYPESENSE_HOST }}
        TYPESENSE_SEARCH_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
        TYPESENSE_COLLECTION: ${{ vars.TYPESENSE_COLLECTION }}
      run: python ImportApiSpecData.py

    - name: Import Markdown Data
      env:
        TYPESENSE_HOST: ${{ vars.TYPESENSE_HOST }}
        TYPESENSE_SEARCH_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
        TYPESENSE_COLLECTION: ${{ vars.TYPESENSE_COLLECTION }}
      run: python ImportMarkdownData.py
